package tcg.pocket.dex

import tcg.pocket.dex.remote.response.Standing

/**
 * Aggregates tournament standings data into deck statistics.
 *
 * This processor groups standings by deck composition and calculates
 * aggregated statistics (count, wins, losses) for each unique deck.
 */
object DeckStatsAggregator {
    /**
     * Aggregates standings into deck statistics.
     *
     * @param standings List of tournament standings to aggregate
     * @return Map of deck ID to aggregated statistics for that deck
     */
    fun aggregate(standings: List<Standing>): Map<String, DeckStats> =
        standings
            .filter { it.deckPokemon.isNotEmpty() }
            .groupBy { createDeckId(it.deckPokemon) }
            .mapValues { (deckId, standingsForDeck) ->
                DeckStats(
                    deckId = deckId,
                    deckName = createDeckName(standingsForDeck.first().deckPokemon),
                    count = standingsForDeck.size,
                    totalWins = standingsForDeck.sumOf { it.wins },
                    totalLosses = standingsForDeck.sumOf { it.losses },
                )
            }

    /**
     * Creates a deterministic deck identifier from Pokemon composition.
     *
     * The identifier is generated by sorting Pokemon names alphabetically
     * and joining them with a separator. This ensures that decks with the
     * same Pokemon composition always produce the same ID.
     *
     * @param pokemon List of Pokemon names in the deck
     * @return Unique identifier for this deck composition
     */
    private fun createDeckId(pokemon: List<String>): String =
        pokemon
            .sorted()
            .joinToString(separator = "|")

    /**
     * Creates a human-readable deck name from Pokemon composition.
     *
     * The name is formatted as "Pokemon1 + Pokemon2 + Pokemon3" with
     * Pokemon sorted alphabetically.
     *
     * @param pokemon List of Pokemon names in the deck
     * @return Human-readable deck name
     */
    private fun createDeckName(pokemon: List<String>): String =
        pokemon
            .sorted()
            .joinToString(separator = " + ")
}
